### ISSUE TITLE
Some images are blurry

### ISSUE THREAD

**Issue by SketchySwift** [MagicSketch/MagicMirror#22]
Some of the images seem to become quite blurry whenever I use the plugin

**Comment by jamztang** [comment]
Thanks, would you mind provide an example Sketch file so we can work on that?

**Comment by zbuechler** [comment]
I noticed this as well and found it is related to corner radius. If I try to refresh a layer after adding a corner radius, the whole thing is blurry. Removing the corner radius and refreshing makes the layer clear again. I can add a corner radius after applying the layer, but any time I need to refresh I must remove corner radius.

**Comment by HardcoreIOS** [comment]
@zbuechler Yeah that's the problem, thanks for bringing that up! I forgot about this conversation 😅

**Comment by HardcoreIOS** [comment]
@jamztang Any chance you can fix the problem @zbuechler had mentioned above?

**Comment by jamztang** [comment]
Magic Mirror 3 should address the issue with Corner Radius support

http://magicsketch.io/mirror
