### ISSUE TITLE
Not working in Sketch 40.3

### ISSUE THREAD

**Issue by SketchySwift** [MagicSketch/MagicMirror#27]
Magic Mirror isn't working in sketch 40.3

**Comment by muppetti** [comment]
Yes, not working. Shit, I need it NOW.

**Comment by mediter** [comment]
Same thing here. Magic Mirror 2.0.4 isn't working in sketch 3.6.1.

**Comment by jamztang** [comment]
There's previous cases where users fixes with the https://github.com/jamztang/MagicMirror/wiki/Troubleshooting guide at issue #26. Would you guys let me know if any of the procedure works there?

So just a reminder, just make sure you're not installing through Sketch Toolbox, we have a compatibility issue with how Sketch Toolbox installs the plugin.

Please keep me updated

**Comment by HardcoreIOS** [comment]
Still having issues :(

**Comment by HardcoreIOS** [comment]
I am **NOT** using sketchtoolbox. I downloaded it straight from the link

**Comment by jamztang** [comment]
@HardcoreIOS Would you mind go through this and file a crash log for me? https://github.com/jamztang/MagicMirror/wiki/Email-Me-for-Support

**Comment by HardcoreIOS** [comment]
I just see a bunch of random stuff in there

**Comment by jamztang** [comment]
Hey guys, please see if v2.0.5 works...

http://api.magicmirror.design/download/latest

**Comment by HardcoreIOS** [comment]
It's working

**Comment by AlfieElizondo** [comment]
2.0.9 Not working with 39.1

**Comment by preethi1123** [comment]
v2.0.9.2 crashes 40.3
