### ISSUE TITLE
Proportions

### ISSUE THREAD

**Issue by mischugo** [MagicSketch/MagicMirror#28]
Hello,
i have a big artboard with a lot of logos (logowall)
When i use the plugin to get the logowall into a smaller rectangle (lets say a banner), all logos lost their proportions. It looks compressed.
May be i have some misunderstanding (?)

**Comment by jamztang** [comment]
Would you mind share a sketch file for that?

**Comment by mischugo** [comment]
Hello,
i send you a file, but the delivery has a fault and couldn’t be done :-(

Do you have a regula mail adress instead of github?

Best
Maik

-- 
Maik Laufender

Absender: Maik Laufender <maiklaufender@gmail.com>
Antworten: Maik Laufender <maiklaufender@gmail.com>
Datum: 6. April 2016 at 14:37:26
Empfänger: jamztang/MagicMirror <reply@reply.github.com>
Betreff:  Re: [jamztang/MagicMirror] Proportions (#28)  






^ VON UNTERWEGS GESENDET ^

Am 06.04.2016 um 12:45 schrieb James Tang <notifications@github.com>:

Would you mind share a sketch file for that?

**Comment by jamztang** [comment]
Sure, please send to this email

james@magicmirror.design

Cheers
James
