### ISSUE TITLE
Broken installation via Sketch Toolbox

### ISSUE THREAD

**Issue by immnk** [MagicSketch/MagicMirror#41]
On clicking of ctrl+shift+m or from menu, the toolbar doesnt pop or show anywhere on the screen. Tried uninstalling and re-installing but of no use

**Comment by mark-github** [comment]
seems to be completely broken

**Comment by jamztang** [comment]
hey guys are you using the latest version 2.0.6 and which version of Sketch you're on?

**Comment by immnk** [comment]
Hey, I'm using the latest version of Magic mirror and **Sketch 3.7.2**

**Comment by immnk** [comment]
Hey, the problem occurs when I'm using latest version of Magic mirror and old version of sketch. When I update Sketch, the issue is gone.

**Comment by jamztang** [comment]
thanks for the report! And also another tip is that you'll have to restart Sketch whenever you update the plugin! Let me know if anything else happens

**Comment by mark-github** [comment]
@jamztang 
Sketch 3.7.2
I just downloaded Magic Mirror 2 last week so I assume it's up to date. I can't tell because every single option under Plugins > Magic Mirror 2 do absolutely nothing. Restarted Sketch many times now, nothing.

**Comment by jamztang** [comment]
Ahh awesome!

**Comment by jamztang** [comment]
I'm renaming this thread so people will see the update when it's fixed
