### ISSUE TITLE
Symbols Not Rendering

### ISSUE THREAD

**Issue by josiahgulden** [MagicSketch/MagicMirror#43]
mirrored symbols aren't rendering. see below... left is the master, right is the mirror. any ideas?

<img width="882" alt="screen shot 2016-04-30 at 9 54 56 am" src="https://cloud.githubusercontent.com/assets/8836050/14936729/b6d01400-0eb9-11e6-8527-6ee1c54dd75f.png">

**Comment by jamztang** [comment]
Please update to the latest version of the plugin and restart Sketch! Cheers

**Comment by duemunk** [comment]
I had the same issue, did the update, and everything works as expected.

**Comment by sogen** [comment]
close!
