### ISSUE TITLE
Sketch unexpectedly quits too often after using Magic Mirror..

### ISSUE THREAD

**Issue by cueforq** [MagicSketch/MagicMirror#54]
I'm Magic Mirror Pro User. After I using Pro Version, Sketch app crashes too much.. I can not concentrate my work. If it does not fixed, I maybe have to get a refund. Thanks.

[Sketch app crash report.txt](https://github.com/jamztang/MagicMirror/files/398962/Sketch.app.crash.report.txt)

**Comment by jamztang** [comment]
Hi @cueforq,

```
Crashed Thread:        10  Dispatch queue: com.bohemiancoding.sketch.coreimage
```

The crashlog is indicating the crash is from SketchMirror, which is official feature of Sketch. Would there be a confusion here?

And also, does Sketch crash even if you never open up the Magic Mirror toobar?

James

**Comment by cueforq** [comment]
thanks for instant reply!

i wasn't using sketch mirror and magic mirror. if it does not relevant with magic mirror, sorry for noise. thanks

**Comment by sogen** [comment]
hi, 2.0.9 crashes on Yosemite
