### ISSUE TITLE
Shows popup every time I resize shape

### ISSUE THREAD

**Issue by reznik** [MagicSketch/MagicMirror#55]
Hi. Magic Mirror shows popup every time I resize shape with Mouse + Shift + Option.
![2016-08-12 12 47 40](https://cloud.githubusercontent.com/assets/5618616/17619029/91d6bfea-608b-11e6-98d1-9cc8e5da2f4f.png)

**Comment by sogen** [comment]
Yes, this is the same as issue #49 and #52 
I see this appear on layers not using MagicMirror

**Comment by jamztang** [comment]
You might want to explicitly set that layer to not use Magic Mirror

<img width="803" alt="screen shot 2016-08-25 at 6 42 08 pm" src="https://cloud.githubusercontent.com/assets/852375/17966357/aa6c40bc-6af3-11e6-9279-852e606d7e55.png">

**Comment by sogen** [comment]
ahh
👍

**Comment by sogen** [comment]
Thought: 
the plugin should by default assume "-- None --" on every single layer
??

because otherwise you have to add "-- None -- " to every layer

**Comment by jamztang** [comment]
It is already by default assumes not to use Magic Mirror, but in some cases, for example an artboard changes its name, some layers depending on that artboard lost track and triggers an error.

**Comment by reznik** [comment]
It doesn't apply -- None -- to the layer. But maybe I'm doing smth wrong. Here's gif for you
![magicmirror-popup](https://cloud.githubusercontent.com/assets/5618616/18213647/f01869e2-7151-11e6-90bc-50f2b830de98.gif)

**Comment by reznik** [comment]
Renaming layer to --None-- helps though

**Comment by jamztang** [comment]
@reznik the reason is that the hearted shape contains curve and it is possibly not having exactly four points, thats why it couldn't be mirrored.
