### ISSUE TITLE
Magic mirror crashes when selecting 4x image resolution

### ISSUE THREAD

**Issue by JulieTorrisi** [MagicSketch/MagicMirror#58]
I just upgraded to pro today and its crashing sketch when I select 4x image quality.

**Comment by jamztang** [comment]
4x results in 16 times larger memory, so that might an issue if the shape was too big. please try in smaller artboard.

Since this seemed to be a Magic Mirror 3 issue, I'll close it here for now.

For more questions please email support@magicsketch.io.
