### ISSUE TITLE
Screen goes blank when updating Sketch v44.1

### ISSUE THREAD

**Issue by qmanning** [MagicSketch/MagicMirror#60]
Have both the most recent version of Sketch & MagicMirror, and have activated the product. I've tried restarting numerous times, with multiple different file-types, images, etc. 

Whenever I click the UPDATE button, the end result is a blank screen.

**Comment by jamztang** [comment]
It seems you're referring to MM3 right? Please make sure you have uninstall all other older versions of MM3 in `~/Library/Application\ Support/com.bohemiancoding.sketch3/Plugins` and restart your Sketch with our latest plugin http://dl.magicsketch.io/mirror3/latest. 

If you need more help, please send us more info through support@magicsketch.io

I'll close this for MM3 right now.
