### ISSUE TITLE
Magic Mirror doesn't work with Sketch 49

### ISSUE THREAD

**Issue by yong2004** [MagicSketch/MagicMirror#64]
Magic mirror was working until version 48 but 49 doesn't work.

**Comment by thatfield** [comment]
Also having this problem now that I've updated to Sketch 49.  Magic Mirror doesn't work.

**Comment by stianmandarin** [comment]
Confirming I have this problem also

**Comment by jkhco** [comment]
Also confirming.

**Comment by yousifa** [comment]
+1. Breaks position and size of assets in inspector is blank

**Comment by JBUXD** [comment]
Seem to be having the same issue. Sketch 49 crashes when MagicMirror is enabled. No particular trigger for the crash. Disabling the plugin has stopped it crashing. 

Is there a fix coming?

**Comment by lojpas** [comment]
Also confirming this issue

**Comment by mickmak-busicat** [comment]
Thanks for reporting the compatibility problem with Magic Mirror and Sketch 49.
We have published latest version 3.5.4 that should work fine on Sketch 49 (Also fixed the position and size text fields problem).
Please update it in Sketch app and restart the program to have a try. Thanks.

**Comment by u2butterfly** [comment]
I have Sketch 49 and just installed Magic Mirror 3.5.5 and it is not working.  It's not updating.  There's no option for "include in artboards."
