### ISSUE TITLE
Sketch 49: Position and size values empty

### ISSUE THREAD

**Issue by MattiaPompei** [MagicSketch/MagicMirror#65]
When the plugin is enabled, all items position and size values fields are empty (they don't change, just aren't visible). They only become visible when I move the item (using arrow keys or mouse).

I disabled the plugin and the issue disappeared.

Thanks

**Comment by mickmak-busicat** [comment]
Sketch 49 has updated the right panel a little bit when custom plugins try to refresh the panel, the position and size text fields will become empty.
We have published 3.5.4 that fixes this problem. Please update the plugin and try. Thanks!
