### ISSUE TITLE
Not working in paid version with Sketch 52.1

### ISSUE THREAD

**Issue by blynkkk** [MagicSketch/MagicMirror#79]

**Comment by assentorp** [comment]
Same here. I'm also a recent paying customer... and it's not working. Really hope for a fix soon as I need this plugin for some client work. I found this in the logs - maybe someone can help with a fix for it:

`Error in command MagicMirror3Panel Script at path /Users/user/Library/Application Support/com.bohemiancoding.sketch3/Plugins/MagicMirror3.sketchplugin/Contents/Sketch/MagicMirror3Panel.framework/MagicMirror3Panel.js does not contain a handler function named: onOpenDocument. «Plugin Output»`

🙏

**Comment by sogen** [comment]
Maybe try asking in Sketch's developers forum:
https://sketchplugins.com/

**Comment by sogen** [comment]
just saw a tweet from October 4:

https://twitter.com/magicsketchio/status/1048023616955138048

"working on fix"

**Comment by sogen** [comment]
btw, why are you still on v2? 
latest is 3.5.9

**Comment by blynkkk** [comment]
Updated, but still no luck. Work is stopped...

**Comment by sogen** [comment]
😮

**Comment by jamztang** [comment]
Hey guys, sorry for the long wait. We've just updated a new version 3.6.2 that should work on Mojave and Sketch 52. We'll close this thread for now and please do bug reporting in the other thread regarding 3.6.2, thanks! https://github.com/MagicSketch/MagicMirror/issues/83
