### ISSUE TITLE
I want to use this, but....

### ISSUE THREAD

**Issue by vikeen** [MagicSketch/MagicMirror#81]
Incompatibility problems, out of date documentation, or lack of explanation.

You have a good product people want, but it just isn't intuitive and filled with bugs. After messing with it for an hour, and installing some different sketch versions in hopes that something would work, I'm giving up.

If you're able, I'd recommend only focusing resources on customer support and onboarding simplicity.

**Comment by jamztang** [comment]
Sorry that the product didn't fit your needs and your feedback. We just released a new version for Sketch 52. We'll review our process and work on it, thanks again.
