### ISSUE TITLE
Just a heads up, the .json in 3.6.1 says 3.5.9

### ISSUE THREAD

**Issue by sogen** [MagicSketch/MagicMirror#82]
thanks for the update, testing :)
FYI the file
https://github.com/MagicSketch/MagicMirror/blob/master/MagicMirror3.sketchplugin/Contents/Sketch/manifest.json
says 3.5.9

**Comment by jamztang** [comment]
Thanks for the heads up Sogen, you beat me into it, just released an update for the correct version number :)
